CI: Validate changelog.md is updated every version bump

diff --git a/tools/testscript b/tools/testscript
--- a/tools/testscript
+++ b/tools/testscript
@@ -146,6 +146,12 @@ build() {
         cabal_install_run_tests dist/*-*.tar.gz --force-reinstalls
 
     fi
+
+    version=`sed -n 's/^version:[[:space:]]*//p' directory.cabal`
+    grep -q "## $version (" changelog.md || {
+        echo >&2 "Error: Please describe version $version in changelog.md."
+        return 1
+    }
 }
 
 "$@"
